export const PermissionCode = {
  // Dashboard
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',

  // Users
  USER_VIEW: 'USER_VIEW',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_STATUS_TOGGLE: 'USER_STATUS_TOGGLE',

  // Students
  STUDENT_VIEW: 'STUDENT_VIEW',
  STUDENT_CREATE: 'STUDENT_CREATE',
  STUDENT_UPDATE: 'STUDENT_UPDATE',
  STUDENT_DELETE: 'STUDENT_DELETE',

  // Mentors
  MENTOR_VIEW: 'MENTOR_VIEW',
  MENTOR_CREATE: 'MENTOR_CREATE',
  MENTOR_UPDATE: 'MENTOR_UPDATE',
  MENTOR_DELETE: 'MENTOR_DELETE',

  // Companies
  COMPANY_VIEW: 'COMPANY_VIEW',
  COMPANY_CREATE: 'COMPANY_CREATE',
  COMPANY_UPDATE: 'COMPANY_UPDATE',
  COMPANY_DELETE: 'COMPANY_DELETE',

  // Groups & Group Rooms
  GROUP_VIEW: 'GROUP_VIEW',
  GROUP_CREATE: 'GROUP_CREATE',
  GROUP_UPDATE: 'GROUP_UPDATE',
  GROUP_DELETE: 'GROUP_DELETE',
  GROUP_ROOM_VIEW: 'GROUP_ROOM_VIEW',
  ADMIN_GROUP_ROOM_VIEW_ALL: 'ADMIN_GROUP_ROOM_VIEW_ALL',

  // Group Tasks
  GROUP_TASK_VIEW: 'GROUP_TASK_VIEW',
  GROUP_TASK_CREATE: 'GROUP_TASK_CREATE',
  GROUP_TASK_UPDATE: 'GROUP_TASK_UPDATE',
  GROUP_TASK_DELETE: 'GROUP_TASK_DELETE',

  // Submissions
  SUBMISSION_VIEW: 'SUBMISSION_VIEW',
  SUBMISSION_CREATE: 'SUBMISSION_CREATE',
  SUBMISSION_GRADE: 'SUBMISSION_GRADE',
  SUBMISSION_DOWNLOAD: 'SUBMISSION_DOWNLOAD',
  SUBMISSION_DELETE: 'SUBMISSION_DELETE',

  // Phases
  PHASE_VIEW: 'PHASE_VIEW',
  PHASE_CREATE: 'PHASE_CREATE',
  PHASE_UPDATE: 'PHASE_UPDATE',
  PHASE_DELETE: 'PHASE_DELETE',

  // Assignments
  ASSIGNMENT_VIEW: 'ASSIGNMENT_VIEW',
  ASSIGNMENT_CREATE: 'ASSIGNMENT_CREATE',
  ASSIGNMENT_UPDATE: 'ASSIGNMENT_UPDATE',
  ASSIGNMENT_CHANGE_STATUS: 'ASSIGNMENT_CHANGE_STATUS',
  ASSIGNMENT_DELETE: 'ASSIGNMENT_DELETE',

  // Evaluation & Assessment
  ASSESSMENT_VIEW: 'ASSESSMENT_VIEW',
  ASSESSMENT_CREATE: 'ASSESSMENT_CREATE',
  ASSESSMENT_SCORE: 'ASSESSMENT_SCORE',
  ASSESSMENT_PUBLISH: 'ASSESSMENT_PUBLISH',

  // Roles & Permissions Settings
  ROLE_VIEW: 'ROLE_VIEW',
  ROLE_PERMISSION_VIEW: 'ROLE_PERMISSION_VIEW',
  PERMISSION_VIEW: 'PERMISSION_VIEW',
  PERMISSION_UPDATE: 'PERMISSION_UPDATE',
} as const;

export type PermissionCodeType = typeof PermissionCode[keyof typeof PermissionCode];
